### ISSUE TITLE
You can create a muss.db.Room

### ISSUE THREAD

**Issue by relsqui** [rlazarus/MUSS#103]
and then this happens:

```
00:42:43 Traceback (most recent call last):
00:42:43   File "/home/reuven/MUSS/muss/server.py", line 86, in lineReceived
00:42:43     self.player.mode.handle(self.player, line)
00:42:43   File "/home/reuven/MUSS/muss/handler.py", line 177, in handle
00:42:43     command().execute(player, args)
00:42:43   File "/home/reuven/MUSS/muss/commands/building.py", line 30, in
00:42:43 execute
00:42:43     new_item = object_class(object_name, owner=player,
00:42:43 location=player)
00:42:43 TypeError: __init__() got an unexpected keyword argument 'location'
```

(because create tries to put it in your inventory, and rooms don't like that)

**Comment by relsqui** [comment]
Upon glancing at db.py, I don't see how to do that test, except after the object is created and before it's stored in the database. Is that the right way to do it or am I missing something?
